### ISSUE TITLE
Build input webm from raw PCM/Opus frames

### ISSUE THREAD

**Issue by wyozi** [Tangent128/webmetro#1]
Hey! This library looks good. I would like to use it for non-webm source audio.

Let's say I'm able to pack my audio data into Opus frames. Would some parts of this library (like ebml writer) be trivially usable for packing the data into .webm container? I saw some webm encoding tests and code, which looks very promising, but I can't really tell how complicated the whole pipeline would be.

I'm asking because the existing webm libraries for Rust don't seem all that good, especially for streaming use.

**Comment by Tangent128** [comment]
Hey; I'm assuming since you closed this you're going a different way, but for completeness:

The `webm.rs` module only covers the elements that the relay server needs to know about, but in principle a fork of it could be extended straightforwardly to any other elements you'd need, and the `ebml.rs` module is pretty generic.

You'd need to implement a function to convert a frame from a codec into a WebM SimpleBlock, which is a little bit-twiddling, and these modules don't liberate you from having to know how a WebM file is laid out, but I could see it being useful utility code if you know the gist of the WebM spec and don't want to deal with the minutia of EBML varints.
